### ISSUE TITLE
Binarizing dataset without rating

### ISSUE THREAD

**Issue by h4iku** [NicolasHug/Surprise#10]
Hi,
I wanted to ask about giving binarized dataset to Surprise which doesn't have any rating. For example in `ml-100k` dataset a user either watched a movie or not without considering any rating..
For this purpose I converted:
```
196	242	3	881250949
186	302	3	891717742
22	377	1	878887116
244	51	2	880606923
166	346	1	886397596
298	474	4	884182806
```
to this:
```
196	242	1
186	302	1
22	377	1
244	51	1
166	346	1
298	474	1
```
and then I read the dataset like this:
```python
reader = Reader(line_format='user item rating', sep='\t', rating_scale=(1, 1))
```
Which it gave me all zero in the result and I know I'm doing it wrong.
Or should I also add not rated (and not watched) movies with 0 rating and read the dataset with `range_scale=(0, 1)`?
```
196	242	1
196	302	0
196	377	0
196	51	0
196	474	0
.
.
.
```
```python
reader = Reader(line_format='user item rating', sep='\t', rating_scale=(0, 1))
```
Can I even do this in Surprise?

Thanks

**Comment by NicolasHug** [comment]
Hi,

Unfortunately no the binary scale [0, 1]  is not supported yet because it leads to very different prediction algorithms than those with gradual rating scales (e.g. [1, 5]). The last solution you proposed would not work either because this would lead to having all the ratings known by the system.

You may want to look at other libraries such as LightFM or MRec, which provide algorithms for implicit ratings.

I'll soon be working on implicit ratings algorithms though, so keep an eye on Surprise ;) !

Nicolas

**Comment by rishabh-vij** [comment]
Hi @h4iku  How did you handle this issue finally? Did you use some other library or found a workaround to use surprise for handling binary ratings?
