### ISSUE TITLE
Please help! Error: The system cannot find the following file

### ISSUE THREAD

**Issue by akkshita96** [NicolasHug/Surprise#110]
(C:\Users\sunny\Anaconda3) C:\Users\sunny\Documents>cd surprise

(C:\Users\sunny\Anaconda3) C:\Users\sunny\Documents\surprise>python setup.py install
C:\Users\sunny\Anaconda3\lib\site-packages\setuptools\dist.py:360: UserWarning: The version specified ('latest') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % self.metadata.version
running install
running bdist_egg
running egg_info
writing scikit_surprise.egg-info\PKG-INFO
writing dependency_links to scikit_surprise.egg-info\dependency_links.txt
writing entry points to scikit_surprise.egg-info\entry_points.txt
writing requirements to scikit_surprise.egg-info\requires.txt
writing top-level names to scikit_surprise.egg-info\top_level.txt
reading manifest file 'scikit_surprise.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'scikit_surprise.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
error: [WinError 2] The system cannot find the file specified

**Comment by NicolasHug** [comment]
Hi,

It looks like you have missed the headline before submitting this issue:

>IMPORTANT PLEASE READ!!!
Before submitting an issue, make sure it hasn't already been addressed by
checking the past issues and the documentation (FAQ, getting started / advanced
usage guide, etc.). In order to let me help you more efficiently, please fill
the different fields below (Description, Steps to reproduce, etc.).
>
>Also, please keep in mind that I develop and maintain this software on my
**free time**. So please, before asking for help, show me that you have already
tried to solve your problem for more than 5 seconds. That would be greatly
appreciated!
>
>Thank you! :)


Feel free to come back to me.
Nicolas

**Comment by akkshita96** [comment]
I did try to solve this issue but I have failed. 
Please help me!
I have cython installed on my system and file build_ext also exists. Don't know why this error "running build_ext
error: [WinError 2] The system cannot find the file specified" is showing up

**Comment by NicolasHug** [comment]
I simply can't help you with so little information. I understand you're trying to install the package but many things are missing: python version, where did you download the sources, why are you not following the instruction guidelines, etc.

Also, please format your post.

**Comment by akkshita96** [comment]
Sorry for the trouble. I have solved the issue. Thanks anyway!

**Comment by NicolasHug** [comment]
Great!
Could you please explain you solution (and what the problem was) so that others can benefit from it?
