### ISSUE TITLE
SVDpp example

### ISSUE THREAD

**Issue by rsandler00** [NicolasHug/Surprise#123]
Hi, I am trying to use SVDpp, but am confused as to how the implicit ratings are entered input into the function. algo.fit() only seems to use the standard explicit ratings. Can an example be provided for ho to use SVDpp?

Thanks

**Comment by NicolasHug** [comment]
Hi,
The orginial SVD++ algorithm only handles explicit ratings. Implicit ratings are created from the explicit ones: if u has rated i, then it's an implicit rating (regardless of the rating value).
So SVD++ is implemented like this in Surprise.

**Comment by rsandler00** [comment]
Got it. It would be really good to allow arbitrary implicit feedback, and also along those lines, arbitrary user features as proposed in Eq. 6 of:  Koren, Y., Bell, R., & Volinsky, C. (2009). Matrix factorization techniques for recommender systems. Computer, 42(8), 30–37. https://doi.org/10.1109/MC.2009.263

**Comment by estebanbouza** [comment]
@NicolasHug this issue is closed, but would you be interested on merging a PR including implicit ratings for SVD++?

**Comment by NicolasHug** [comment]
It depends...
If the work-around for implicit ratings is only related to SVD++ then no, because I'd like to support implicit ratings at a greater scale (I'm currently working on it but it takes time and a lot of thought).

**Comment by estebanbouza** [comment]
Thanks for the quick response. In that case I won't be doing it, as I don't have that much availability to write code for all algorithms.

**Comment by NicolasHug** [comment]
Sure, no worries (it's even a pain for me :) )

There are other easier issues if you want to contribute!

**Comment by Zooraper** [comment]
Hi, I am now working on my thesis using SVDpp model in Surprise, and since I am not a native English user, the meaning of ' if u has rated i, then it's an implicit rating'  is pretty ambiguous for me.I have read the documentation on SVDpp, but I don't quite understand how the default value of yj(a new set of item factors that capture implicit ratings) is actually set. Appreciate it a lot if you have time to rescue me!
Thanks!

**Comment by NicolasHug** [comment]
Try reading the paper, it might be clearer than what I can explain. Basically SVD++ takes into account explicit ratings and implicit ratings. It's trained on Movielens which only contains explicit ratings, e.g. u rated i with a rating r=4. In order to simulate implicit ratings, the authors decided that an implicit rating exists if there is a r in [1, 5] such that u rated i with explicit rating r.

**Comment by Zooraper** [comment]
@NicolasHug Thanks for your time!I should be going to get myself some paper to read to understand the algorithm thoroughly!
