### ISSUE TITLE
Online Learning

### ISSUE THREAD

**Issue by balajibalasubramanian** [NicolasHug/Surprise#15]
I am making a movie recommendation website. I am using matrix factorization using SVD.
I would be having new users signing up and rating movies. I am not sure how to go about the online learning part of it. Can you give me a suggestion ? Does the library have features that make this easier ?

**Comment by balajibalasubramanian** [comment]
The item matrix would remain constant , I am not adding new movies. Only the user matrix would be changing.

**Comment by NicolasHug** [comment]
Hi,

Unfortunately no, Surprise does not support incremental updates for now but this is one of the tracks I plan to work on.

If you want to try it yourself, I think the best and simplest way to add new ratings to the model is simply to run the vanilla SGD procedure, but instead of randomly initializing the factors, you just use the current values that you ended up with after the main training stage. This avoid retraining on the whole dataset.

I don't know if that's very clear... you tell me ^^ !

**Comment by balajibalasubramanian** [comment]
ok thanks.
