### ISSUE TITLE
Remove numpy dependency for installation

### ISSUE THREAD

**Issue by gbrova** [NicolasHug/Surprise#187]
#### Description

Installation via pip should automatically install all requirements, including numpy.  This is helpful in a continuous integration setting, where setting up the environment with `pip install -r requirements.txt` is quite common (and doesn't currently work for Surprise). 

#### Steps/Code to Reproduce

I tested on both a CircleCI Docker container and a Ubuntu container.  Easiest way to reproduce is in docker, but I get the same result by publishing a simple project to circleci.  

```
➜  ~ docker run -it circleci/python:3.6.5  # same results with ubuntu
$ bash
circleci@54577d1f4689:/$ cd tmp
circleci@54577d1f4689:/tmp$ echo "joblib==0.12.0
> numpy==1.14.5
> scikit-surprise==1.0.6
> scipy==1.1.0
> six==1.11.0" > requirements.txt
circleci@54577d1f4689:/tmp$ 
circleci@54577d1f4689:/tmp$ pip install -r requirements.txt
Collecting joblib==0.12.0 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/f4/2f/66db8ecbfa71cd36146d894c867b2f595682d620329fd823c5c041687b5f/joblib-0.12.0-py2.py3-none-any.whl (261kB)
    100% |████████████████████████████████| 266kB 16.8MB/s 
Collecting numpy==1.14.5 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/68/1e/116ad560de97694e2d0c1843a7a0075cc9f49e922454d32f49a80eb6f1f2/numpy-1.14.5-cp36-cp36m-manylinux1_x86_64.whl (12.2MB)
    100% |████████████████████████████████| 12.2MB 3.9MB/s 
Collecting scikit-surprise==1.0.6 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/4d/fc/cd4210b247d1dca421c25994740cbbf03c5e980e31881f10eaddf45fdab0/scikit-surprise-1.0.6.tar.gz (3.3MB)
    100% |████████████████████████████████| 3.3MB 16.7MB/s 
    Complete output from command python setup.py egg_info:
    Please install numpy>=1.11.2 first.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-9bs19soh/scikit-surprise/
circleci@54577d1f4689:/tmp$ 
```

#### Likely cause
This almost definitely happens because we try to import numpy in setup.py. Is there a way to avoid this?  For example, https://stackoverflow.com/a/42163080 might be a way forward. 

#### Installation from requirements file works (on some environments) if numpy is in the pip cache

On my environment, if numpy happens to be in the pip cache, then installation from requirements.txt succeeds even if numpy is not present in the virtualenv. (!)

```
[user@machine tmp]$ virtualenv -p python3 env
Running virtualenv with interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/user/tmp/env/bin/python3
Also creating executable in /home/user/tmp/env/bin/python
Installing setuptools, pip, wheel...done.
[user@machine tmp]$ source env/bin/activate
(env) [user@machine tmp]$ python -c "import numpy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
(env) [user@machine tmp]$ 
(env) [user@machine tmp]$ pip install -r requirements.txt 
Collecting joblib==0.12.0 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/f4/2f/66db8ecbfa71cd36146d894c867b2f595682d620329fd823c5c041687b5f/joblib-0.12.0-py2.py3-none-any.whl
Collecting numpy==1.14.5 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/68/1e/116ad560de97694e2d0c1843a7a0075cc9f49e922454d32f49a80eb6f1f2/numpy-1.14.5-cp36-cp36m-manylinux1_x86_64.whl
Collecting scikit-surprise==1.0.6 (from -r requirements.txt (line 3))
Collecting scipy==1.1.0 (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/a8/0b/f163da98d3a01b3e0ef1cab8dd2123c34aee2bafbb1c5bffa354cc8a1730/scipy-1.1.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting six==1.11.0 (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Installing collected packages: joblib, numpy, six, scipy, scikit-surprise
Successfully installed joblib-0.12.0 numpy-1.14.5 scikit-surprise-1.0.6 scipy-1.1.0 six-1.11.0
(env) [user@machine tmp]$ 

```

But if we `rm -rf ~/.cache/pip` and retry then the above installation will fail. 

This is true on my local machine, but not in the barebones docker environment. 

This behavior seems very strange, and I'm not familiar enough with pip and python packaging to try to explain it.  But, it could explain why most regular users (who probably installed numpy some time in the past) don't run into this issue. 

#### Workaround

My current workaround is to `pip install numpy` and then `pip install -r requirements.txt` in ths environment setup.  However, having to manually keep track of installation dependencies seems a little strange. 

#### Versions

```
>>> import platform; print(platform.platform())
Linux-4.17.2-1-ARCH-x86_64-with-debian-9.4
>>> import sys; print("Python", sys.version)
Python 3.6.5 (default, Jun  6 2018, 19:19:24) 
[GCC 6.3.0 20170516
```

**Comment by NicolasHug** [comment]
Yeah I definitely agree, the ideal scenario would be to not need numpy before installing surprise.

The pitch basically is:

- some of the code in surprise is written in Cython.
- for optimization, Cython is able to take advantage of the numpy low level library
- when you install surprise from the PyPI source dist (i.e. running `pip install scikit-surprise`) or from the sources, Cython will compile some code to C code. This C code will then be compiled to an extension (.so, .dll...) by a regular C compiler, which can finally be used as a regular Python module (e.g. `import similarities`). As Cython uses numpy's low-level API, your environment needs to know where the numpy headers are for the compilation to happen.

That's why numpy needs to be installed **before** you install surprise, and that's why we need `include_dirs=np.get_include()`, and that's why numpy needs to be imported in setup.py as you mentioned.

When I was packaging surprise I wasn't experienced at all with all this (and I'm not much more experienced now), so I went for the current solution after hours of research. I was partly comforted in my choice by the fact that scikit learn also requires scipy and numpy to be installed beforehand, even though the packaging is a bit different there.

I think I tried subclassing `build_ext` like mentioned in your link, but didn't go for it for some reason (can't be 100% sure though, so it might still be an option).

If you have other ideas I'd be happy to hear them.

-----

A clean and user-friendly solution would be to keep the packaging as is, but distribute wheels instead of source distributions, which would avoid the need to compile the sources each time you install surprise. This would require using various CI services. I'd love to see that happen but honestly I just don't want to spend time on this myself, it's too much of a hassle to manage all of the CI services as there is basically one for each platform.

**Comment by Salokin42** [comment]
Maybe a solution can be found here:
https://github.com/pypa/pip/issues/5761

I have the same problem when wanting to install surprise via pip's requirements.txt in GoogleAppEngine. Trying to find a Work around right now.

**Comment by marcosfede** [comment]
this seems helpful, can you consider adding it to the package? https://luminousmen.com/post/resolve-cython-and-numpy-dependencies

**Comment by bmilovanovic** [comment]
@Salokin42, have you found a solution in GAE?

**Comment by Salokin42** [comment]
Unfortunately no. I used another algorithm and package in the end. Don't
exactly remeber which, could have been scipy.

Boro Milovanovic <notifications@github.com> schrieb am Do., 22. Aug. 2019,
02:52:

**Comment by NicolasHug** [comment]
I've release version 1.1.0 (should be the last one), if anybody can tell me if the problem is fixed that would be greatly appreciated. Thanks!

**Comment by GeoffreyPlitt** [comment]
Worked! Thanks.
