### ISSUE TITLE
algo.predict function returns PredictionImpossible for user = 0 and item = 0 for 100k dataset  

### ISSUE THREAD

**Issue by adideshp** [NicolasHug/Surprise#19]
Hi,
   While testing the predict function for SVD algorithm I observed that the predict function returns was_impossible = True in the details section of Prediction Object. I have mentioned the details below. 
 
Dataset : 100k dataset (Default)
Algorithm : SVD
Validation : 3 Folds cross validation

the predict function associated with the algorithm object returns PredictionImpossible True for user = 0 with any combination of item id (in range). PredictionImpossible is also returns True for item = 0 with any combination of user id (in range)
Check logs below :
For User = 0
algo.trainset.knows_user(0)
True
algo.trainset.knows_item(1)
True
algo.predict('0','1',4)
Prediction(uid='0', iid='1', r_ui=4, est=3.5444502774861255, details={u'reason': '', u'was_impossible': True})

For Item = 0
algo.trainset.knows_user(1)
True
algo.trainset.knows_item(0)
True
algo.predict('1','0',4)
Prediction(uid='1', iid='0', r_ui=4, est=3.5444502774861255, details={u'reason': '', u'was_impossible': True})

Predictions work for other inputs:
algo.predict('1','10',4)
Prediction(uid='1', iid='10', r_ui=4, est=2.7008138081499409, details={u'was_impossible': False})

algo.predict('4','10',4)
Prediction(uid='4', iid='10', r_ui=4, est=4.0589210159479157, details={u'was_impossible': False})

Thanks!

**Comment by NicolasHug** [comment]
Hi,

This is due to the fact that the `knows_user` or `knows_item` methods take inner ids as arguments, while the `predict` method takes raw ids: see [this note](http://surprise.readthedocs.io/en/v1.0.2/getting_started.html#raw-inner-note).

If you look at the ml100k dataset, you will see that there is no user whose id is `'0'`. The first id is `'1'`.

As a side note, the mapping from raw ids to inner ids is quite arbitrary so the raw id `'1'` will not generally be mapped to the inner id `1`.

Hope it helped,

Nicolas

**Comment by adideshp** [comment]
Hi Nicolas,
                  Thanks a lot for your help :) 

Aditya
