### ISSUE TITLE
Parallelization not using all cores (RandomizedSearchCV/GridSearchCV)

### ISSUE THREAD

**Issue by eithompson** [NicolasHug/Surprise#195]
#### Description

I am running RandomizedSearchCV with SVD (~7 million ratings in my dataset) on an AWS machine with 32 cores. Since I am using 5-fold CV and `n_iter = 10`, 50 tasks are spawned. However, at any given moment, only a handful of cores (between 1 and 5) are being used. Because of this, the 50 tasks finish one at a time, in sequence, with roughly the same amount of time between them, instead of the less-sequential timings you would expect with parallelization. 

This could have something to do with the following warning (which you can see in the screenshots):
`/home/ec2-user/anaconda2/lib/python2.7/site-packages/joblib/externals/loky/process_executor.py:634: UserWarning: A worker timeout while some jobs were given to the executor. You might want to use a longer timeout for the executor.
  "the executor.", UserWarning`

#### Steps/Code to Reproduce
Using custom data with ~7M ratings on a 32 core machine.

`cv_iterator = KFold(n_splits = 5, random_state = 23)`
`param_dists = {'n_factors': randint(2,100),
              'lr_all': uniform(0.001, 1),
              'reg_all': uniform(0.001, 0.02)}`
`gs = RandomizedSearchCV(SVD, param_dists, n_iter = 10,
     measures=['rmse', 'mae', 'fcp'], cv=cv_iterator, joblib_verbose = 1000, n_jobs = -1)`

#### Expected Results
All 50 tasks being executed, with 32 at a time (one for each core).

#### Actual Results
https://i.imgur.com/e2yuBLl.jpg
https://i.imgur.com/SBwh6jX.png
#### Versions
platform: `Linux-4.14.47-64.38.amzn2.x86_64-x86_64-with-glibc2.2.5`
sys.version: `('Python', '2.7.15 |Anaconda, Inc.| (default, May  1 2018, 23:32:55) \n[GCC 7.2.0]')`
surprise version: `('surprise', '1.0.6')`

**Comment by NicolasHug** [comment]
The `n_jobs` parameters is only valid for the grid search. As you're doing 5 folds CV, you're only using 5 cores.

The SVD algorithm is (in its original version, i.e. the one of surprise) not parallel. There are parallel versions but I'm not familiar with them.

-------

Sorry for the delay, I was sure I answered before but I was on the subway and apparently the message wasn't sent :/

**Comment by thusithaC** [comment]
Hi, I know the case is closed but your answer didn't make much sense to me. I'm having the same issue, i.e. despite having a beefy machine, only a couple of cores are being utilized during the parameter optimization using Grid Search. Any reason why the different parameter combos are not evaluated at the same time? in this given example surely more than 5 jobs can be run in parallel since there are multiple parameter combos that can be evaluated simultaneously?

**Comment by NicolasHug** [comment]
The original author assumed that the `n_iter` from SVD should have an impact on the parallelization, but it does not.

> As you're doing 5 folds CV, you're only using 5 cores

But indeed I was wrong here. As you mentionned the potential number of jobs is `n_splits * n_candidates`.

I have 4 cores on my machine, and if I set n_jobs to -1 with 3 folds, I still see the 4 cores being used. So that would suggest that the code works correctly.

Maybe it has to do in the way you have configured `joblib`?

Can you run this and tell me what you see?

```py
from sklearn import svm, datasets
from sklearn.model_selection import GridSearchCV
X, y = datasets.make_classification(n_samples=10_000)
parameters = {'kernel':('linear', 'rbf'), 'C':[1, 2, 3, 4]}
svc = svm.SVC(gamma="scale")
clf = GridSearchCV(svc, parameters, cv=3, n_jobs=-1)
clf.fit(X, y)
```

This should potentially spawn 3 * 8 = 24 processes.

**Comment by thusithaC** [comment]
Hi @NicolasHug Thanks for checking. 

I tried your snippet, and indeed it does spawn many processors and i can see all 16 threads in my PC going 100% for few seconds before completing the work.
 
However, the issue persists with my code/dataset. Wonder if it is something to do with my Dataset or how I call the CV. 
This is my code snippet. 
```from surprise import SVD
from surprise import Dataset
from surprise.model_selection import GridSearchCV

from surprise import Reader, Dataset
reader = Reader(rating_scale=(0,1))

data = Dataset.load_from_df(data_train_scored[['user_id', 'item_id', 'score']], reader)

param_grid = {
    "n_epochs": [5, 10],
    "lr_all": [0.002, 0.005],
    "reg_all": [0.4, 0.6]
}
gs = GridSearchCV(SVD, param_grid, measures=["rmse", "mae"], cv=5, n_jobs=-1)

display("starting cv")
gs.fit(data)```

However, when executing I can see only one or two CPU active 100%. The training is slow, and after a while I get timeout messages. I'm wondering if I should try some other parameter-optimization toolbox like hyperopt and see how things go. I can confirm if I just use svd.fit(), the training process works fine. 

![image](https://user-images.githubusercontent.com/7017511/67487692-f5c46580-f6a0-11e9-9696-5e35659908cd.png)
