### ISSUE TITLE
Adding MovieLens 20M dataset to built-in datasets

### ISSUE THREAD

**Issue by tomasprinda** [NicolasHug/Surprise#229]
[MovieLens 20M dataset](https://grouplens.org/datasets/movielens/20m/).

I changed scripts and I wanted to create a branch and push it to repository and I got 
```
fatal: Authentication failed for 'https://github.com/NicolasHug/Surprise.git/'
```

Am I doing something wrong or what is the correct way of creating pull request?

**Comment by NicolasHug** [comment]
You'll find more detailed explanations on the web (especially on github docs) but to submit a PR you first need to fork this repo, then clone your fork, do the changes here, push them to your fork and only then can you make the PR.

You can't directly create a PR (or push changes to a any branch) in this repo because you don't have commit rights.

That being said, unless you can prove me wrong, algorithms with ml20m run take a looot of time right? I tried SVD with ml10m, and it was already pretty slow. I don't think it's a good idea to have built-in support for datasets that are this big if no algorithm can run them in a reasonnable time. We still support them of course, but not built-in. Let me know if you can run them fast!

**Comment by tomasprinda** [comment]
Thanks for help.

Yes it takes a bit longer (SVD 80 minutes) and takes about 10GB memory. 

The benchmark table that you have in README was very useful for me and I needed the same for bigger data. Even though it runs a long time I wanted to know how long. For that purpose I used ML20M. So I thought other people might be interested in the same so I wanted to make their life easier. 

I will create pull request and leave it up to you if you use it or no.

**Comment by NicolasHug** [comment]
Ok, thanks a lot for the feedback.

As it is so long I'd rather not include it as a built-in. Users can still use it of course, by defining a custom `Reader` object.

Thanks a lot anyway!

**Comment by NicolasHug** [comment]
Closing (https://github.com/NicolasHug/Surprise/issues/229#issuecomment-441330871), thanks for the PR anyway!
