### ISSUE TITLE
how to compile a .pyx file after modification

### ISSUE THREAD

**Issue by ngovind93** [NicolasHug/Surprise#232]
Hi NicolasHug,
am trying to compile the pyx file after modifying some code. with cython am compiling.  it is compiling without any errors. but it is not reflecting when I run the program.
how it should be done??

Thank you in advance

**Comment by NicolasHug** [comment]
Just use `pip install -e .`

**Comment by ngovind93** [comment]
am unable to get through it. I have made changes on my system and I want to compile it.

~/.local/lib/python2.7/site-packages/surprise$ pip install  -e

am getting this:


Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

-e option requires an argument

**Comment by NicolasHug** [comment]
@ngovind93 , unless it's for a legit bug, I'll stop answering your questions.

You have a history of asking me to do your homework (and deleting your posts when I call you on it...), and you come ask for help on unrelated things here, instead of just using google.

Have you even read my answer? Have you even read the error message?

`pip install -e .`

there's a `.` at the end. The error message is precisely saying `-e option requires an argument`. You need to read it.

Please stop wasting my time.

**Comment by ngovind93** [comment]
~/.local/lib/python2.7/site-packages/surprise$ pip install -e  .
i already tried with that also. i got this error.

Directory '.' is not installable. File 'setup.py' not found.
Y
