### ISSUE TITLE
GridSearch on pre-defined folds.

### ISSUE THREAD

**Issue by TamTSE2301** [NicolasHug/Surprise#243]
Hi,

I want to tune hyperparamters by using your GridSearchCV function. The problem is that in my cross validation, i need to divide the folds first then apply some pre-processing procedures on training set before applying KNN or SVD.

Do you have any suggestion of how to use GridSearchCV for cases of pre-defined folds like me?

Thank you in advance.

Best,

Tam.

**Comment by NicolasHug** [comment]
What exactly is the preprocessing you need?

I assume your problem is that you don't want any "data leak" that would bias your grid search results. Unfortunately there is no generic way of doing this in surprise since we do not support pipelines (like scikit-learn does). But depending on what the preprocessing is there might be some hacks...

**Comment by TamTSE2301** [comment]
First, we take 4/5 folds as trainingset.
Then, we remove global effect based on ridge regression.
After that, we take the residuals and use surprise alogrithm (KNN or SVD) to predict the other fold.

**Comment by NicolasHug** [comment]
I see.

I think the only way for it to work correctly is if you create your own pipeline, that is wrap the preprocessing and the following prediction algorithm (KNN or SVD) into a single `AlgoBase` object

**Comment by TamTSE2301** [comment]
Thanks for your quick reponse. I would try your suggestion.
