### ISSUE TITLE
Dimension of qi smaller than the number of items

### ISSUE THREAD

**Issue by jeremyborg** [NicolasHug/Surprise#294]
I have a pandas dataframe containing 22,378 different users and ratings for 1,065 different items (games). After using SVDpp to train the model, I wanted to plot the items according to their qi value, to try to understand what each latent factor is representing. My problem is that the size of the latent factors, which I obtained through algo.qi, is smaller than the number of items. This means that I cannot map the qi values to the respective games. My code is as follows:

```
# Load data from pandas dataframe
reader = Reader(rating_scale=(1,5))
data = Dataset.load_from_df(cleaned_player_game[['username','gamename','star_rating']], reader)

# Train SVDpp with 5 latent factors using 3 fold cross validation
algo=SVDpp(n_factors=5)
cross_validate(algo, data, measures=['MAE'], cv=3, verbose=True)

# Iterate over trainset to get the ordered list of items according to their inner iid.
# This will then be used to match the qi values with the corresponding item
games = []
trainset = data.build_full_trainset()
for i in range(0,trainset.n_items):
    games.append(trainset.to_raw_iid(i))
```

The problem is that `algo.qi.shape` returns (1058,5) but `trainset.n_items` returns 1065. To my understanding and according to [issue 119](https://github.com/NicolasHug/Surprise/issues/119), algo.qi.shape should be an array of shape (n_items, n_factors). So in this case it should be (1065,5) and not (1058,5).

Why is qi missing 7 items?

EDIT:
After further investigation, it appears that the issue is related to the cross_validate method, because the shape of algo.qi changes according to the cv value. Smaller cv values result in a smaller algo.qi shape

**Comment by NicolasHug** [comment]
Yes the size of qi is the number of items in the training set. There might be less items in the training set due to subsampling because of the cross validation.

I'm not sure what you want to do, but using cross_validate to train a model doesn't make much sense: the model you end up with is just the model trained on the last folds. If you want to tune parameters you might want to consider GridSearch, or you can also just train on the full trainset (please refer to the docs)
