### ISSUE TITLE
k-NN-based algorithms use too much memory

### ISSUE THREAD

**Issue by asross** [NicolasHug/Surprise#3]
I tried using this library to make k-NN-based recommendations for a dataset with about 10,000 items and 150,000 users, but when I do, my OS always kills the process running `surprise` for using too much memory. SVD and SVD++ work just fine, though.

Have you tested the `knns` module with that much data, and do you have any thoughts about what causes it in particular to fail? I glanced through the code and on the off-chance the issue is the call to `sorted`, it would be relatively simple to avoid sorting the entire set of neighbors, and instead just scan through them once, storing a running list of the `k` most similar.

**Comment by NicolasHug** [comment]
Hi, thanks for the feedback.

I haven't tried kNN algorithms with that much data no. Are you certain that the memory issue happens when calling `sorted`? I would rather think it happens when the similarity matrix is computed, because this matrix is of size `|U| * |U|` which is very large in your case.
This may not be what you want but [computing similarities between items](http://surprise.readthedocs.io/en/latest/prediction_algorithms.html#similarity-measure-configuration) instead of between users will reduce memory usage, and hopefully avoid the whole issue.

I'm afraid I don't properly understand what you mean by 
>  it would be relatively simple to avoid sorting the entire set of neighbors, and instead just scan through them once, storing a running list of the k most similar.

The thing with the set of neighbors is that it is always relative to the current user `u` and the current item `i`, because you need to find the `k`  users closest to `u` that have rated `i`, so I fail to see how any precomputation would help here. Maybe you meant that for every user, we should sort all the other users by order of similarity once and for all?

**Comment by asross** [comment]
> Are you certain that the memory issue happens when calling sorted?

No, not at all, that was just an off the cuff guess 😄  It sounds like the memory issue is definitely the one you described (assuming that's only an issue for kNN and not for SVD). If it's possible to avoid working with that matrix all at once when it won't fit in memory, that might it possible to apply Surprise's implementation of kNNs to larger datasets.

> I'm afraid I don't properly understand what you mean by
> 
> > it would be relatively simple to avoid sorting the entire set of neighbors, and instead just scan through them once, storing a running list of the k most similar.

I wasn't suggesting any precomputation; I was just hypothesizing that [this line](https://github.com/NicolasHug/Surprise/blob/master/surprise/prediction_algorithms/knns.py#L104) might be the cause of the issues, and if it was, you could fix it by not calling `sorted` on that list (which makes a copy of it and maybe is memory-inefficient) but instead just looping through that list and keeping track of the top `k`. In general you never need to sort a list to find its maximum entry (or its maximum several entries).

But basically, if the problem is just in `compute_similarities` (rather than in sorting its rows), then you could imagine avoiding memory problems by never computing that matrix and instead taking on extra computational complexity. 

Anyway, this is just food for thought... if you do test kNN with lots of data, see the same problem, and end up coming up with a fix for whatever is causing it, that'd be excellent, but if not, no prob!

**Comment by NicolasHug** [comment]
Ho I see! You're right that the `sort` could be optimized (using [argpartition](https://docs.scipy.org/doc/numpy/reference/generated/numpy.argpartition.html) for example), but I never really bothered about it as the current sort takes `O(n log(n))` where `n` is the number of users that have rated the item, and it's usually not a huge number. The bottleneck here definitely seems to be the matrix computation.

The matrix computation could be avoided, but during the prediction step we would still need to compute the similarities between the current user and all other users. So when you need to predict more than one rating for a given user, you end up doing the same computation multiple times (that's why the similarity matrix is currently precomputed at the training stage). I never tried to implement it because I never thought people would want to wait such a long time ^^, and so far all other libraries I've looked at also precompute the matrix. But if you think this may be worth it, I may take a look at it. Any suggestion on where to start?

BTW, is the dataset you're using available online by any chance? 

> (This is also a cool library, thank you for writing it!)

Thanks :) ! Just out of curiousity, may I ask where you heard about surprise?

**Comment by asross** [comment]
> The matrix computation could be avoided, but during the prediction step we would still need to compute the similarities between the current user and all other users. So when you need to predict more than one rating for a given user, you end up doing the same computation multiple times (that's why the similarity matrix is currently precomputed at the training stage). I never tried to implement it because I never thought people would want to wait such a long time ^^, and so far all other libraries I've looked at also precompute the matrix. But if you think this may be worth it, I may take a look at it. Any suggestion on where to start?

Maybe using a scipy.sparse representation of the matrix could help? Don't have any crystal clear ideas though.

> BTW, is the dataset you're using available online by any chance?

Yes, I'm working with the [Yelp Challenge dataset](https://www.yelp.com/dataset_challenge)! It's pretty big.

> Thanks :) ! Just out of curiousity, may I ask where you heard about surprise?

Was just Googling around for Python recommendation libraries. I'm working on a recommender system project for a class, and wanted to compare some ideas we had to baseline implementations of matrix factorization and nearest-neighbor methods. We also tried GraphLab Create and Vowpal Wabbit -- yours has prettier documentation, though :)

**Comment by NicolasHug** [comment]
> Maybe using a scipy.sparse representation of the matrix could help? Don't have any crystal clear ideas though.

I'm afraid that wouldn't help here, as the matrix is completely dense. However, as all of surprise's similarity measures are symmetric, we could use a symmetric matrix and divide memory usage by 2. But unfortunately there's no clean built-in symmetric in numpy or scipy (that I know of)...

Thanks for the link, I'll take a look at it!

**Comment by NicolasHug** [comment]
Hey, comming back to you on this.

I had some time and tried a few workarounds for computing similarities on the fly to use less memory, but unfortunately none of what I tried fitted nicely with the current workflow (plus it was awefully slow). I'm afraid there's no easy/clean way to do it right now.

Memory usage is a typical drawback of neighboorhood methods and as far as I know there's no way reduce memory usage while keeping a decent running time. 

If you're OK with it I'll close the issue?
Thanks,
Nicolas

**Comment by asross** [comment]
I would definitely buy that figuring out a performant workaround for those issues is difficult or impossible, and especially since neighborhood models aren't generally as good anyway, it probably isn't worth the time-investment to establish that definitively :) Thank you so much for putting in the time and effort to figure out a solution though!
