### ISSUE TITLE
ask for your help

### ISSUE THREAD

**Issue by ZGHS** [NicolasHug/Surprise#307]
First very thank you for your framework.
I run SVDpp on two similar dataset ,one gets result,another shows nothing. Why?
I will thank you so much ,if you could help me.

**Comment by NicolasHug** [comment]
Sorry, can't help you with so few info...

**Comment by ZGHS** [comment]
> 
> 
> Sorry, can't help you with so few info...

![微信图片_20191101113421](https://user-images.githubusercontent.com/31759691/68000577-a29f7380-fc9b-11e9-8e98-2c76d38b25de.jpg)
![微信图片_20191101113414](https://user-images.githubusercontent.com/31759691/68000584-a7fcbe00-fc9b-11e9-9324-9c9c174522cf.jpg)


[Desktop.zip](https://github.com/NicolasHug/Surprise/files/3796581/Desktop.zip)



source file and dataset are in the zip file。


![批注 2019-11-01 114025](https://user-images.githubusercontent.com/31759691/68000823-8e0fab00-fc9c-11e9-84e1-140b80e561bb.png)

**Comment by NicolasHug** [comment]
That's because the testset is empty for the second dataset

`testset = trainset.build_anti_testset()`

You are building the anti testset which is all the ratings that are not in the training set. But your second dataset is complete: all users have rated all items, so there is nothing to have a prediction for.
