### ISSUE TITLE
How 'RMSE', 'MAE' helps in building a correct Rc system?

### ISSUE THREAD

**Issue by dilipbobby** [NicolasHug/Surprise#57]
Theoretically, I have gone through the RMSE and MAE but I did not understand how they help us in building a correct Rc system ? Can you help in explaining those Rmse and MAE in simple words.
when I use my own data set which looks like movielens data.I'm getting following values 

        Fold 1  Fold 2  Fold 3  Mean    
MAE     5.4207  5.4768  5.4711  5.4562  
RMSE    6.4610  6.5579  6.6052  6.5414

**Comment by ha0x7c7** [comment]
These two values actually determines how good you were at predicting the rating value for unknown items,
difference between MAE and RMSE is how much we penalize failing at prediction, in MAE if your model don't predict the rating value, a small value is added to error, but in RMSE it is different.

**Comment by dilipbobby** [comment]
hmm .. looks like I'M understanding what you are saying.Can you explain same looking at my values of MAE and RMSE @ha0x7c7

**Comment by NicolasHug** [comment]
Algorithms predict ratings. RMSE and MAE evaluate how accurate are these predictions.

MAE computes the average error. We use the absolute value for each error (r_ui - est_ui), else some errors would be negative which makes no sense.

RMSE does quite the same thing, expect that instead of taking the absolute value we square the errors. This has the effect of having only positive errors as well, but big errors are heavily penalized. To obtain a number which is of the dimension of a rating (error), we take the root.


Your RMSE of 5 means that your predictions are, in average, off by 5 points.

As a side note, this is a bug tracker. Your question would probably more suited somewhere on reddit or stackexchange.

Nicolas
