### ISSUE TITLE
Add warning on README

### ISSUE THREAD

**Issue by muzavan** [NicolasHug/Surprise#86]
Hi, I notice from the `load_from_dataframe.py` example, there are steps to train your data from Dataframe object. However, I can't do this on my surprise installation because of the `Dataset.load_from_df` does not exist. I have tried upgrading my surpriselib using pip but the issue still persist. 

![image](https://user-images.githubusercontent.com/5964406/30648551-802819d2-9e48-11e7-9144-666b11e8d4a0.png)

However, after search in this repository, I found it in the source code. I guess this happened because the surpriselib on pip is not updated with current source code.

I think it's better to put some warning in the README file to warn user about this possible issue and recommend user to build from the source.

Awesome library btw!

**Comment by NicolasHug** [comment]
Hi,
and thanks!

Indeed this feature has been added recently and it hasn't been released on PyPI yet (hence installing surprise with pip won't give you `load_from_df`). 

I'll add a warning on the example file rather than on the readme so that it's clear that this feature is only available on the lastest version. I'll have to remove it once the release is out though...


Nicolas
